### ISSUE TITLE
ViewModel should implement UILifeCycle interface

### ISSUE THREAD

**Issue by HNeukermans** [Nilzor/mvp-to-mvvm-transition#1]
Dear,

I am a developer myself, with many years of experience in Silverlight (WPF), MVVM.

In your Fragment implementation, I saw following code: 

public void onViewCreated(View view, Bundle savedInstanceState) {
        ensureModelDataIsLodaded();
    }

The way i managed to deal with view lifecycle events in an MVVM, Silverlight environment, was to create an interface (ex: IUILifeCycle) that exposed all the viewevents from the native rendering platform, and have those viewmodels implement that interface. 
With that in place your code would look like

public void onViewCreated(View view, Bundle savedInstanceState) {
        viewModel.onUIViewCreated();
    }

The benefit of having a IUILifeCycle interface, is that you can test,  the load- behavior of the view.
In general you can say that, with an interface like that it is possible to test the lifecycle behavior of your view. :-).

This way you can test that indeed the loadAsync method is called, when the view is created only for the first time. because the code beneath would move into your viewmodel. 

if (!mViewModel.isLoaded()) {
            mViewModel.loadAsync();
        }

**Comment by Nilzor** [comment]
See my comment in #2 

Basically, I disagree that it is a _must_ for the ViewModel to care about the lifecycle of the View. The only good argument I see is that it's a common pattern to always load the data in `onCreate()`. 

Memory leaks are not an argument (again see #2) and testability is neither - you can unit test the life cycle of the view either using Android instrumentation tests or through mocking/stubbing frameworks such as Robolectric and Mockito. 

I appreciate the input though - you and other might want to implement that pattern, but I don't see it as an outright fault with this example project, hence I close this issue.
