### ISSUE TITLE
[Question] - MVVM on M

### ISSUE THREAD

**Issue by blundell** [Nilzor/mvp-to-mvvm-transition#3]
Would you say only use MVVM if minSdk is M? or should I be looking into using this architecture in all apps with some type of backport?

**Comment by Nilzor** [comment]
You don't need minSdk M for using databinding! You only need targetSdk M (or 23 now). That said you can use the MVVM pattern without data binding as well, but data binding really makes it shine by ridding of the boilerplate Model-To-View-code and to some extent View-To-Model.

Sorry for late answer, didn't see this before now.
