### ISSUE TITLE
how can i get the edittext's text value in viewmodel?

### ISSUE THREAD

**Issue by qingfengmy** [Nilzor/mvp-to-mvvm-transition#4]
in viewmodel , i need check up the username and password when login. and how could i get the edittext 's text value(like name and password) when i click login button.

**Comment by Nilzor** [comment]
There are a couple of different approaches to this: 
1. Manually read off the values when user clicks Login. See the LoginFragment in master branch for example: https://github.com/Nilzor/mvp-to-mvvm-transition/blob/master/app/src/main/java/com/nilzor/presenterexample/ui/LoginFragment.java
2. Implement some sort of "two way data binding" by tapping into the textChanged events of the EditText. a) I have implemented one explicit way in the `two-way-explicit` branch: https://github.com/Nilzor/mvp-to-mvvm-transition/tree/twoway-explicit . Here I manually set the event hooks in the layouts: `android:afterTextChanged="@{data.onUsernameChanged}"/>`. But I also have implemented an implicit binding b) in the https://github.com/Nilzor/mvp-to-mvvm-transition/tree/two-way-implicit branch after the pattern from Fabio Collini: https://medium.com/@fabioCollini/android-data-binding-f9f9d3afc761#.solhsqt8l . 

PS: Sorry for late answer didn't see this before now
